language: python

python:
  - "3.5"

script:
  - ./tests.sh

notifications:
  email: true
  slack:
    rooms:
      - appliedmpc:fU25pTj0itFJQp9ycTEFXI2F
    on_success: change
    on_failure: always

os:
  - linux
