language: python

python:
  - "3.5"

script:
  - nosetests

notifications:
  email: true
  slack:
    rooms:
      - appliedmpc:Q3gSuYu4bSpenmQ5KZHRPvHc
    on_success: change
    on_failure: always

os:
  - linux
